name: Build Haxe Project

on:
  push:
    branches: feature/pages-deploy

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Setup Haxe Libs
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup

      - name: Build project
        run: lime build html5

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: export/html5/bin
          SINGLE_COMMIT: true
