name: Build Haxe Project

on:
  push:
    branches: 
      - master
    tags:
      - v*

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Setup Haxe Libs
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib run lime setup flixel --quiet

      - name: Build project
        run: haxelib run lime build html5
        
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: export/html5/bin
          SINGLE_COMMIT: true

      - name: Deploy to A.D.S. Games
        if: startsWith(github.ref, 'refs/tags/v')
        uses: adsgames/deploy-to-adsgames@main
        with:
          project-id: superarcherman
          version: ${{ steps.get_version.outputs.VERSION }}
          build-dir: export/html5/bin
          platform: WEB
          bucket-access-key: ${{ secrets.LINODE_BUCKET_ACCESS_KEY }}
          bucket-secret-key: ${{ secrets.LINODE_BUCKET_SECRET_KEY }}
          api-key: ${{ secrets.ADSGAMES_API_KEY }}
